version: '3.9'
services:
  artemis:
    image: local/artemis
    container_name: artemis
    ports:
      - 61616:61616
      - 5672:5672
      - 8161:8161
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 400M
    environment:
      - ARTEMIS_USER=user
      - ARTEMIS_PASSWORD=pass
      # - ANONYMOUS_LOGIN=true

  activemq:
    image: local/activemq
    container_name: activemq
    build: 
      context: ./docker/activemq/
    ports:
      - 61617:61616
      - 5673:5672
      - 8080:8161
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 400M
    environment:
      - ACTIVEMQ_ADMIN_LOGIN=user
      - ACTIVEMQ_ADMIN_PASSWORD=pass
    #   - ANONYMOUS_LOGIN=true

  rabbitmq:
    image: rabbitmq:3.9.13-management-alpine
    container_name: rabbitmq
    ports:
      - 15672:15672
      - 5674:5672
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 400M

  nginx:
    image: nginx:1.21
    container_name: nginx
    volumes:
      - ./docker/nginx:/etc/nginx/conf.d
    ports:
      - 80:80
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 20M
    depends_on:
      - server

  redis:
    container_name: redis
    image: redis:6-alpine
    command: redis-server --requirepass Redis2022!
    ports:
      - 6379:6379
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 100M

  server:
    container_name: server
    image: node-filas
    build:
      context: .
    command: npm run server
    volumes:
      - ./:/usr/app/
    env_file:
      - ./.env
    environment:
      - rabbit_host=rabbitmq
      - active_host=activemq
      - artemis_host=artemis
    ports:
      - 3333:3333
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 150M
    depends_on:
      - redis
      - artemis
      - activemq
      - rabbitmq

  consumer:
    container_name: consumer
    image: node-filas
    build:
      context: .
    command: npm run consumer
    volumes:
      - ./:/usr/app/
    env_file:
      - ./.env
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 150M
    depends_on:
      - server
    