version: '3.9'
services:
  artemis:
    image: local/artemis
    container_name: artemis
    ports:
      - 61616:61616
      - 5672:5672
      - 8161:8161
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 400M
    # environment:
    #   - ARTEMIS_USER=user
    #   - ARTEMIS_PASSWORD=pass
    #   - ANONYMOUS_LOGIN=true

  activemq:
    image: local/activemq
    container_name: activemq
    build: 
      context: ./docker/activemq/
    ports:
      - 61617:61616
      - 5673:5672
      - 8080:8161
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 400M
    # environment:
    #   - ACTIVEMQ_ADMIN_LOGIN=user
    #   - ACTIVEMQ_ADMIN_PASSWORD=pass
    #   - ANONYMOUS_LOGIN=true

  rabbitmq:
    image: rabbitmq:3.9.13-management-alpine
    container_name: rabbitmq
    ports:
      - 15672:15672
      - 5674:5672
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 400M
